name: Build audio segmentation extraction plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
    - uses: actions/checkout@v3
    - name: Build the Docker image    
      run: |
        docker build -t audio-segmentation .
        docker tag audio-segmentation ghcr.io/netherlandsforensicinstitute/audio-segmentation:latest
        docker push ghcr.io/netherlandsforensicinstitute/audio-segmentation:latest
